name: user
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  pin_entry_text_field: ^0.1.4
  firebase_auth: ^0.15.4
  intl: ^0.16.1
  json_annotation: ^3.0.1
  flutter_phoenix: ^0.1.0
  country_code_picker: ^1.3.15
  grouped_buttons: ^1.0.4
  google_fonts: ^1.1.0
  image_auto_slider: ^0.0.3
  image_slider: ^1.0.2
  pin_code_text_field: ^1.7.1
  page_transition: ^1.1.6
  shared_preferences: ^0.5.10
  toast: ^0.1.5
  circular_bottom_navigation: ^1.0.1
  carousel_slider: ^2.3.1
  url_launcher: ^5.7.2
  shimmer_animation: ^0.1.1
  path_provider: ^1.6.14
  horizontal_calendar_widget: ^1.0.2
  razorpay_flutter: ^1.2.2
  flutter_paystack: ^1.0.4+1
  flutter_share: ^1.0.2+1
  geolocator: ^6.0.0+4
  geocoder: ^0.2.1
  google_maps_flutter: ^1.0.3
  flutter_google_places: ^0.2.6
  flutter_local_notifications: ^2.0.0
  firebase_messaging: ^5.0.1
  sqflite: ^1.3.1+1
  progress_dialog: ^1.2.4
  image_picker: ^0.6.7+11
  flutter_datetime_picker: ^1.4.0
  flutter_html: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.4.1
  intl_translation: ^0.17.9
  flutter_launcher_icons: ^0.8.1
  change_app_package_name: ^0.1.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logos/logo_user.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
    - images/account/
    - images/address/
    - images/custom/
    - images/footermenu/
    - images/icons/
    - images/logos/
    - images/maincategory/
    - images/veg/
    - images/veg/Sellers/
    - images/veg/Vegetables/
    - images/payment/
    - images/demosliderimage/
    - images/refernearn/
    - assets/
    - assets/category/
    - assets/products/
    - assets/restaurant/
    - assets/slider/
    - assets/user_profile/
    - assets/payment/
    - assets/onboarding/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages